In [2]:
import numpy as np

marks = np.array([10, 20, 30, 40])

print(marks)


[10 20 30 40]


In [3]:
a = np.array([9.2, 5.8, 7.8, 5.7])

print(a)

[9.2 5.8 7.8 5.7]


In [4]:
import numpy as np

marks = np.array([10, 20, 30, 40])

print(marks)


[10 20 30 40]


In [5]:
a = np.array([10, 20, 30, 40])

print(a)

[10 20 30 40]


In [6]:
a = np.array([10, 20, 30, 40])

print(a.ndim)

1


In [7]:
a = np.array([
    [1,2,3],
    [4,5,6]
])

print(a)

[[1 2 3]
 [4 5 6]]


In [8]:
a = np.array([
    [1,2,3],
    [4,5,6]
])

print(a.ndim)

2


In [9]:
a = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
a = np.array([
   [[1,2,3]],
    [[4,5,6]],
    [[7,8,9]]
])

print(a.ndim)

3


In [11]:
a = np.array([
    [1,2,3],
    [4,5,6]
])

print(a.shape)  #Shape of Array

(2, 3)


In [12]:
a = np.array([
    [1,2,3],
    [4,5,6]
])

print(a.size)  #Size of Array

6


In [13]:
import numpy as np

data_4d = [
    [
        [[1, 2], [3, 4]],
        [[5, 6], [7, 8]]
    ],
    [
        [[9, 10], [11, 12]],
        [[13, 14], [15, 16]]
    ]
]

a = np.array(data_4d)

print(a)
print("Dimension:", a.ndim) # Output: 4
print("Shape:", a.shape)    # Output: (2, 2, 2, 2)

[[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]]


 [[[ 9 10]
   [11 12]]

  [[13 14]
   [15 16]]]]
Dimension: 4
Shape: (2, 2, 2, 2)


In [14]:
a = np.array([
    [1,2,3],
    [4,5,6]
])

print(a.dtype)  #datatype of Array

int32


In [15]:
a = np.array([
              [1,2,3],
              [4,5,6]
])

print("Array:", a)        #Array
print("Size", a.size)   #Size Of Array
print("Dimensions:", a.ndim)   #Dimensions of Array
print("Shape:", a.shape)  #Shape of Array
print("Data Type:", a.dtype)  #Data Type


Array: [[1 2 3]
 [4 5 6]]
Size 6
Dimensions: 2
Shape: (2, 3)
Data Type: int32


In [16]:
#Creating Special Arrays

#Array of Zeros 

import numpy as np

a = np.zeros((3, 4))

print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [17]:
#Array of Ones

import numpy as np

a = np.ones((3, 4))

print(a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [18]:
#Array of Four

import numpy as np

a = np.full((3, 4), 4)

print(a)

[[4 4 4 4]
 [4 4 4 4]
 [4 4 4 4]]


In [19]:
#Identity Matrix

a = np.eye(4)

print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [20]:
#Array of Two

a = np.full((3, 4), 2)

print(a)

[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]


In [21]:
#Empty Array

a = np.empty((2, 2))

print(a)

[[1. 1.]
 [1. 1.]]


In [22]:
my_list = [2, 3]
print(my_list[0])  # 2
print(my_list[1])  # 3

2
3


In [23]:
my_tuple = (2, 3)
print(my_tuple[0])  # 2
print(my_tuple[1])  # 3

2
3


In [24]:
#Creating Number Sequences

#Arrange()


import numpy as np

a = np.arange(1, 11)

print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [4]:
#Gap of Two

a = np.arange(0, 20, 2)

print(a)

[ 0  2  4  6  8 10 12 14 16 18]


In [10]:
#Arange Number

a = np.arange(12)

print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [11]:
#Convert into Matrix

b = a.reshape(3, 4)

print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [14]:
#Convert of Matrix

a = np.arange(12)

b = a.reshape(3, 4)

print(a)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [15]:
#Flattening

#Convert matrix into Row

a = np.array([[1,2],[3,4]])

print(a.flatten())

[1 2 3 4]


In [18]:
#Indexing

a = np.array([10, 20, 30, 40])

print(a[0])
print(a[1])
print(a[2])
print(a[3])
print(a[-1])    #Last Element

10
20
30
40
40


In [19]:
import numpy as np

arr = np.array([30, 10, 50, 20, 40])

# 1. Array ko sort karein
sorted_arr = np.sort(arr)
print("Sorted Array:", sorted_arr)  

# 2. Last element nikalne ke liye [-1] use karein
last_element = sorted_arr[-1]
print("Last Element:", last_element)

Sorted Array: [10 20 30 40 50]
Last Element: 50


In [20]:
import numpy as np

b = np.array([
    [ [1, 2, 3], [4, 5, 6] ],     
    [ [7, 8, 9], [10, 11, 12] ]   
])


print(b[0, 1, 2])  
print(b[1, 0, 1])  

6
8


In [21]:
#Slicing

a = np.array([10,20,30,40,50])

print(a[1:4])

[20 30 40]


In [23]:
#Mthematical Operation

a = np.array([10, 20, 30])
b = np.array([1, 2, 3])

#Addition
print( a + b )

#Subtraction
print( a - b )

#Multiplication
print( a * b )

#Division
print( a / b )

#Modulus
print( a % b )

#Square
print( a ** b )

[11 22 33]
[ 9 18 27]
[10 40 90]
[10. 10. 10.]
[0 0 0]
[   10   400 27000]


In [24]:
#Numbers b/w 1 to 20

a = np.arange(1,20)

print(a)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [27]:
#Array of Zeroes

a = np.zeros((4,4))

print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [29]:
#Array of Identity

a = np.eye((3))

print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [36]:
#Array of Shape

a = np.array([[1, 2, 3, 7, 8],
             [4, 5, 6, 9 , 0]
])

print("Shape:", a.shape)

Shape: (2, 5)


In [37]:

a = np.arange(12)
b = a.reshape([3,4])

print(a)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [42]:
#Maximum And Minimum

a = np.array([1, 2, 3, 7, 8])

print("Max:", a.max())
print("Min:", a.min())

Max: 8
Min: 1


In [49]:
#Mean, Median and Standard Deviation

a = np.array([12, 18, 25, 30, 45])

print("Average:", a.mean())
print("Median:", np.median(a))
print("Standard Deviation:", np.std(a))

Average: 26.0
Median: 25.0
Standard Deviation: 11.29601699715435


In [55]:
# Ascending and Decending Order

import numpy as np

a = np.array([1, 18, 5, 30, 4])

# Ascending Order
a.sort()
print("Ascending:", a)

# Descending Order
desc = a[::-1]
print("Descending:", desc)

Ascending: [ 1  4  5 18 30]
Descending: [30 18  5  4  1]


In [1]:
# Simple Calculator
a = float(input("Enter first number: "))
op = input("Enter operator (+, -, *, /): ")
b = float(input("Enter second number: "))

if op == '+':
    print("Result:", a + b)
elif op == '-':
    print("Result:", a - b)
elif op == '*':
    print("Result:", a * b)
elif op == '/':
    print("Result:", a / b if b != 0 else "Cannot divide by zero")
else:
    print("Invalid operator")

Enter first number:  7
Enter operator (+, -, *, /):  +
Enter second number:  5


Result: 12.0


In [6]:
#String Array
import numpy as np
a = np.array(["Bike", "car", "Motor"])

print(a)

['Bike' 'car' 'Motor']


In [7]:
#Universal Functions
a = np.array([1, 4, 9, 16])

print(np.sqrt(a))

[1. 2. 3. 4.]


In [9]:
a = np.array([1, 4, 9, 16])

print(np.exp(a))   #Exponential
print(np.abs(a))   #Absolate
print(np.log(a))   #Logarithm
print(np.tan(a))   #Tangent
print(np.sin(a))   #Sine
print(np.cos(a))   #Cosine
print(np.sqrt(a))  #Square

[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]
[ 1  4  9 16]
[0.         1.38629436 2.19722458 2.77258872]
[ 1.55740772  1.15782128 -0.45231566  0.30063224]
[ 0.84147098 -0.7568025   0.41211849 -0.28790332]
[ 0.54030231 -0.65364362 -0.91113026 -0.95765948]
[1. 2. 3. 4.]


In [10]:
#COPY and VIEW

a = np.array([1,2,3])
b = a.copy()
b[0] = 100
c = a.view()
c[0] = 100

print(a)
print(b)



[100   2   3]
[100   2   3]


In [11]:
#Broadingcasting

a = np.array([1,2,3])

print(a + 10)

[11 12 13]


In [13]:
#Example of Real Life: Student Marks

marks = np.array([65,72,85,90,78])

print("Average:", np.mean(marks))
print("Highest:", np.max(marks))
print("Lowest:", np.min(marks))

Average: 78.0
Highest: 90
Lowest: 65


In [16]:
import numpy as np

np.random.seed(42)
salaries = np.random.randint(30000, 120000, size=50)

new_salaries = salaries * 1.05

print("New Salaries after 5% Increment:\n", np.round(new_salaries, 2))
print("Employee Salaries:\n", salaries)
print("-----------------------------------")
print("Mean (Average) Salary:", np.mean(salaries))
print("Maximum Salary:       ", np.max(salaries))
print("Minimum Salary:       ", np.min(salaries))

New Salaries after 5% Increment:
 [ 48084.75  32403.   112161.    89130.3   38078.25 118005.3   70553.7
 123372.9   77837.55  94776.15  48324.15  74644.5  102082.05  99561.
  32307.45  94221.75  97602.75  99671.25 102867.45  37076.55 118759.2
  87892.35 121070.25  61627.65 107028.6   58440.9  120201.9   50852.55
  34384.35  93607.5  100511.25 120386.7   69061.65 102306.75  91230.3
 101643.15  64628.55  43463.7  104046.6   35584.5   75186.3  115539.9
 123178.65  42658.35  40731.6  109167.45  76651.05 111879.6   56591.85
 103055.4 ]
Employee Salaries:
 [ 45795  30860 106820  84886  36265 112386  67194 117498  74131  90263
  46023  71090  97221  94820  30769  89735  92955  94925  97969  35311
 113104  83707 115305  58693 101932  55658 114478  48431  32747  89150
  95725 114654  65773  97435  86886  96803  61551  41394  99092  33890
  71606 110038 117313  40627  38792 103969  73001 106552  53897  98148]
-----------------------------------
Mean (Average) Salary: 78745.34
Maximum Salary:    

In [17]:
#Random Number
a = np.array([1,2,3])

print(np.random.rand(5))

[0.23089383 0.24102547 0.68326352 0.60999666 0.83319491]


In [20]:
#Random Interger
import numpy as np
a = np.array([1,2,3])

print(np.random.randint(1,100,10))

[35 78 81 36 50  4  2  6 54  4]


In [22]:
#Random Matrix
a = np.array([1,2,3])

print(np.random.randint(1,50,(3,4)))

[[14 23 40 21]
 [16 45 18 47]
 [24 26 25 45]]


In [23]:
#Boolean FIltering

marks = np.array([45,60,75,30,90])

print(marks > 50)
print(marks[marks > 50])

[False  True  True False  True]
[60 75 90]


In [24]:
a = np.zeros(3)

print(a)

[0. 0. 0.]


In [3]:
from sklearn.cluster import KMeans
import numpy as np

data = np.array([
    [2, 3],
    [3, 4],
    [10, 12],
    [11, 13]
])

model = KMeans(n_clusters=2, random_state=42)
model.fit(data)

print("Cluster Labels:")
print(model.labels_)

/lib/python3.14/site-packages/threadpoolctl.py:1135: RuntimeWarning: JsProxy.as_object_map() is deprecated. Use as_py_json() instead.
  for filepath in LDSO.loadedLibsByName.as_object_map():


Cluster Labels:
[0 0 1 1]
